COREMARK_PATH = /home/zfu/rios/apd_from_lab1/apd/tb/test_program/coremark/coremark.riscv
DHRYSTONE_PATH = /home/zfu/rios/apd_from_lab1/apd/tb/test_program/coremark/coremark.riscv


run_coremark:
	cargo run --release $(COREMARK_PATH)

run_dhrystone:
	cargo run --release $(DHRYSTONE_PATH)